# Training and test data sets for training and/or metrics evaluation
data:
  training:
    # Specify directory path to training dataset
    data_dir: /lustre/fswork/projects/rech/ynx/commun/simulated_datasets/data/v1xx/
    # Provide name of training dataset
    file: v1.3.0-train.npy
    # if training data set file does not exist, generate a new one by setting values below
    stars: null
    positions: null
    SEDS: null
    zernike_coef: null
    C_poly: null
    params: # 
      d_max: 2
      max_order: 45
      x_lims: [0, 1000.0]
      y_lims: [0, 1000.0]
      grid_points: [4, 4]
      n_bins: 20
      max_wfe_rms: 0.1
      oversampling_rate: 3.0
      output_Q: 3.0
      output_dim: 32
      LP_filter_length: 2
      pupil_diameter: 256
      euclid_obsc: true
      n_stars: 400
  test:
    # Specify directory path to training dataset
    data_dir: /lustre/fswork/projects/rech/ynx/commun/simulated_datasets/data/v1xx/
    # Provide name of test dataset
    file: v1.3.0-test.npy
    # If test data set file not provided produce a new one
    stars: null
    noisy_stars: null
    positions: null
    SEDS: null
    zernike_coef: null
    C_poly: null
    parameters:
      d_max: 2
      max_order: 45
      x_lims: [0, 1000.0]
      y_lims: [0, 1000.0]
      grid_points: [4,4]
      max_wfe_rms: 0.1