#Change checkpoint and sense_map path
checkpoint_dir: /lustre/fswork/projects/rech/rbn/ulx23va/projects/unrolled_cGAN/checkpoint_dir/trained_radio_cGAN_models/v2_batch_10/
data_path: /lustre/fswork/projects/rech/rbn/ulx23va/projects/unrolled_cGAN/datasets/new_radio_GAN/

# Define the experience
experience: radio

# Logging 
wandb_offline: True

# Number of code vectors for each phase
num_z_test: 32
num_z_valid: 8
num_z_train: 2

# Data
in_chans: 2  # Real+Imag parts from obs
out_chans: 1
im_size: 256 #384x384 pixel images

# Options
alt_upsample: False # False -> convt upsampling, True -> interpolate upsampling
norm: macro # none, micro, macro

# Optimizer:
lr: 0.001
beta_1: 0.
beta_2: 0.99

# Loss weights
gp_weight: 10
adv_weight: 1e-5

# Training
batch_size: 10 # per GPU
accumulate_grad_batches: 1
# Gradient accumulation is not automatic in pytorch v2>

#Remember to increase this for full training
num_epochs: 100
psnr_gain_tol: 0.25

num_workers: 4
