"""Compare the phentax waveform before and after the get_time_of_frequency fix.

Two stages, driven by ``compare_waveforms.slurm``:

    python compare_waveforms.py --variant old   # imports a pristine phentax
    python compare_waveforms.py --variant new   # imports the patched phentax
    python compare_waveforms.py --plot

``--variant old`` prepends a copy of the phentax source tree whose
``core/phase.py`` is the committed (pre-fix) version, so both variants can be
measured from the same job without touching the working repo.

Three draws are compared:

* ``standard``     -- an ordinary test source, far from the failing region.
* ``near_failure`` -- the failing parameter vector with eta nudged to 0.145,
  the first value the OLD solver could still handle. The closest point to the
  bug where a before/after comparison is even possible.
* ``failing``      -- the actual failing vector (eta = 0.10077). The old code
  raises here, so there is no "before" curve to draw; that is the point.
"""

import argparse
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))  # tracked repo dir
DATA_IN = os.path.join(HERE, "..", "data")         # tracked inputs
T = "/lustre/fswork/projects/rech/ney/ulx23va/projects/LISA/outputs/testing"  # outputs
OLD_SRC = f"{T}/hm_diag/phentax_old_src"  # regenerated by the job; not tracked
BAD_CHI1Z = 0.5775
BOUNDARY_ETA = 0.145  # first eta the pre-fix solver managed at BAD_CHI1Z


def _select_draws(cfg, thetas, names):
    """Return {label: (theta, description)} for the three comparison draws."""
    i_eta, i_c1 = names.index("reduced_mass"), names.index("chi1z")

    with open(os.path.join(DATA_IN, "failing_theta.json")) as f:
        bad = json.load(f)
    bad_vec = np.array([bad[n] for n in names], dtype=np.float64)

    # A standard source: the reference draw with eta furthest from the failing
    # region, i.e. the least pathological one available.
    standard = thetas[int(np.argmax(thetas[:, i_eta]))].astype(np.float64)

    near = bad_vec.copy()
    near[i_eta] = BOUNDARY_ETA

    return {
        "standard": (standard, f"standard draw (eta={standard[i_eta]:.4f}, "
                               f"chi1z={standard[i_c1]:+.3f})"),
        "near_failure": (near, f"near the failure (eta={BOUNDARY_ETA}, "
                               f"chi1z={BAD_CHI1Z})"),
        "failing": (bad_vec, f"the failing draw (eta={bad_vec[i_eta]:.5f}, "
                             f"chi1z={BAD_CHI1Z})"),
    }


def compute(variant):
    if variant == "old":
        sys.path.insert(0, OLD_SRC)

    import jax

    jax.config.update("jax_enable_x64", True)
    import jax.numpy as jnp

    import phentax

    print(f"variant={variant}  phentax from {phentax.__file__}")

    from lisajax_sbi.utils import DataGenerationConfig
    from lisajax_sbi.waveforms import build_waveform_model

    import h5py

    with h5py.File(f"{T}/data/test_jean_zay_dataset_phentax_hm.h5", "r") as f:
        cfg = DataGenerationConfig.model_validate(json.loads(f.attrs["config"]))
        n_total = f["xs"].shape[0]
        idx = np.arange(n_total)
        np.random.default_rng(0).shuffle(idx)
        test_idx = idx[int(n_total * 0.8) + int(n_total * 0.1):]
        thetas = f["thetas"][sorted(test_idx[:100])][:24]

    names = [p.name for p in cfg.params]
    draws = _select_draws(cfg, thetas, names)

    wf = build_waveform_model(
        "phentax", delta_t=cfg.dt, f_min=cfg.f_min, f_ref=cfg.f_ref,
        higher_modes=cfg.higher_modes,
    )
    # Fix the window so both variants use an identical time grid.
    tc_max = max(p.bounds[1] for p in cfg.params if p.name == "coalescence_time")
    m_max = max(p.bounds[1] for p in cfg.params if p.name == "total_mass")
    wf.configure_window(
        t_obs_start=0.0,
        t_obs_end=cfg.n_ts * cfg.dt,
        tc_max=float(tc_max),
        total_mass_max=float(m_max),
    )

    out = {}
    for label, (theta, desc) in draws.items():
        params = {n: theta[i] for i, n in enumerate(names)}
        try:
            conv = wf._convert_params(params)
            times, mask, hp, hc = wf._run_phentax(T=wf._T, **conv)
            times, hp, hc = (np.asarray(times).ravel(), np.asarray(hp).ravel(),
                             np.asarray(hc).ravel())
            m = np.asarray(mask).ravel().astype(bool)
            out[f"{label}__ok"] = np.array(True)
            out[f"{label}__t"] = times
            out[f"{label}__hp"] = np.where(m, hp, 0.0)
            out[f"{label}__hc"] = np.where(m, hc, 0.0)
            out[f"{label}__mask"] = m
            print(f"  {label:13s} OK   n={m.sum()} |hp|max={np.abs(hp[m]).max():.4e}")
        except Exception as exc:  # noqa: BLE001
            out[f"{label}__ok"] = np.array(False)
            out[f"{label}__err"] = np.array(type(exc).__name__)
            print(f"  {label:13s} FAILED ({type(exc).__name__})")
        out[f"{label}__desc"] = np.array(desc)

    path = f"{T}/hm_diag/waveforms_{variant}.npz"
    np.savez_compressed(path, **out)
    print("SAVED", path)


def plot():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    a = np.load(f"{T}/hm_diag/waveforms_old.npz", allow_pickle=False)
    b = np.load(f"{T}/hm_diag/waveforms_new.npz", allow_pickle=False)

    labels = ["standard", "near_failure", "failing"]
    fig, axes = plt.subplots(3, 3, figsize=(17, 11))

    for r, label in enumerate(labels):
        desc = str(b[f"{label}__desc"])
        ok_a, ok_b = bool(a[f"{label}__ok"]), bool(b[f"{label}__ok"])

        if not ok_b:
            for c in range(3):
                axes[r, c].text(0.5, 0.5, "new version also failed",
                                ha="center", va="center", transform=axes[r, c].transAxes)
            continue

        t = b[f"{label}__t"]
        hp_b, hc_b = b[f"{label}__hp"], b[f"{label}__hc"]
        m = b[f"{label}__mask"]

        # --- column 1: full waveform, both versions -----------------------
        ax = axes[r, 0]
        if ok_a:
            ax.plot(a[f"{label}__t"][a[f"{label}__mask"]],
                    a[f"{label}__hp"][a[f"{label}__mask"]],
                    lw=2.4, alpha=0.45, color="tab:blue", label="previous")
        ax.plot(t[m], hp_b[m], lw=0.9, color="tab:red", label="current")
        ax.set_title(f"{desc}\n$h_+$ (full)", fontsize=9)
        ax.set_xlabel("t [s, geometric]")
        ax.legend(fontsize=8)
        if not ok_a:
            ax.text(0.02, 0.93, f"previous: CRASHED\n({str(a[f'{label}__err'])})",
                    transform=ax.transAxes, fontsize=9, color="tab:blue", va="top",
                    bbox=dict(fc="white", ec="tab:blue", alpha=0.85))

        # --- column 2: zoom on the last part (merger/ringdown) ------------
        ax = axes[r, 1]
        tv = t[m]
        lo = tv[int(0.985 * len(tv))]
        sel_b = m & (t >= lo)
        if ok_a:
            ta, ma = a[f"{label}__t"], a[f"{label}__mask"]
            sel_a = ma & (ta >= lo)
            ax.plot(ta[sel_a], a[f"{label}__hp"][sel_a], lw=2.8, alpha=0.45,
                    color="tab:blue", label="previous")
        ax.plot(t[sel_b], hp_b[sel_b], lw=1.0, color="tab:red", label="current")
        ax.set_title("$h_+$ zoom (merger / ringdown)", fontsize=9)
        ax.set_xlabel("t [s, geometric]")
        ax.legend(fontsize=8)

        # --- column 3: absolute difference --------------------------------
        ax = axes[r, 2]
        if ok_a and a[f"{label}__t"].shape == t.shape:
            dhp = np.abs(a[f"{label}__hp"] - hp_b)
            dhc = np.abs(a[f"{label}__hc"] - hc_b)
            scale = np.abs(hp_b[m]).max()
            ax.semilogy(t[m], np.maximum(dhp[m], 1e-300), lw=0.8,
                        color="tab:purple", label=r"$|\Delta h_+|$")
            ax.semilogy(t[m], np.maximum(dhc[m], 1e-300), lw=0.8,
                        color="tab:green", alpha=0.7, label=r"$|\Delta h_\times|$")
            ax.axhline(scale, color="k", ls=":", lw=1,
                       label=f"$\\max|h_+|$ = {scale:.2e}")
            ax.set_title(
                f"absolute difference\nmax$|\\Delta h_+|$ = {dhp.max():.3e}  "
                f"(rel {dhp.max() / scale:.2e})", fontsize=9)
            ax.legend(fontsize=8)
        else:
            msg = ("no previous waveform to difference\n"
                   "(previous version crashed here)" if not ok_a
                   else "time grids differ; not comparable pointwise")
            ax.text(0.5, 0.5, msg, ha="center", va="center",
                    transform=ax.transAxes, fontsize=10)
            ax.set_title("absolute difference", fontsize=9)
        ax.set_xlabel("t [s, geometric]")

    fig.suptitle(
        "phentax waveform before vs after the get_time_of_frequency fix "
        "(higher modes [21, 33, 44, 55])", fontsize=12)
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    out = f"{T}/hm_diag/waveform_comparison.png"
    fig.savefig(out, dpi=150)
    print("SAVED", out)

    # --- numeric summary --------------------------------------------------
    print("\n=== SUMMARY ===")
    for label in labels:
        ok_a, ok_b = bool(a[f"{label}__ok"]), bool(b[f"{label}__ok"])
        if ok_a and ok_b:
            dhp = np.abs(a[f"{label}__hp"] - b[f"{label}__hp"])
            scale = np.abs(b[f"{label}__hp"]).max()
            print(f"  {label:13s} previous=OK      current=OK   "
                  f"max|dhp|={dhp.max():.3e}  rel={dhp.max()/scale:.3e}")
        else:
            print(f"  {label:13s} previous={'OK' if ok_a else 'CRASHED'}  "
                  f"current={'OK' if ok_b else 'CRASHED'}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--variant", choices=["old", "new"])
    p.add_argument("--plot", action="store_true")
    args = p.parse_args()

    if args.plot:
        plot()
    else:
        compute(args.variant)
