# Define paths
dataset_path: /lustre/fswork/projects/rech/ynx/ulx23va/datasets/TNGgals/raw
save_dir: /lustre/fswork/projects/rech/ynx/ulx23va/projects/projects-ns/trained_models/TNGgals/unet/24-08-22-18:49:00
trained_model_path: /lustre/fswork/projects/rech/ynx/ulx23va/projects/projects-ns/trained_models/TNGgals/unet/24-08-22-18:49:00/ckp_99.pth.tar

# Experiment and run name for wandb 
experiment: unet_TNGgals
run_name: flipschitz_unet

# Data
dataset_name: TNGgals
patch_size: 256
train_datapoints: 2
eval_datapoints: 2
test_datapoints: 2
use_gray_imgs: True
in_channels: 1
out_channels: 1
# dataset_name: `BSD`, `TNGgals` 
# if `test_datapoints` is `0`, then the number of original images in the dataet is used.

train_batch_size: 1
test_batch_size: 1
num_workers: 4

# Denoiser
denoiser_name: unet
pretrained_init: False
sigma_train: 0.059
sigma_min: 0
sigma_max: 0




