# Define paths
checkpoint_dir: /lustre/fswork/projects/rech/ynx/ulx23va/projects/projects-ns/trained_models/TNGgals/dncnn/
dataset_path: /lustre/fswork/projects/rech/ynx/ulx23va/datasets/TNGgals/raw

# Experiment name
experiment: dncnn_TNGgals
run_name: full_train_dncnn_TNGgals

# Data
dataset_name: TNGgals
patch_size: 204
train_datapoints: 5e4
eval_datapoints: 1e3
test_datapoints: 0
use_gray_imgs: True
in_channels: 1
out_channels: 1
# dataset_name: `BSD`, `TNGgals` 
# if `test_datapoints` is `0`, then the number of original images in the dataet is used.


# Denoiser
denoiser_name: dncnn
sigma_train: 0.059
sigma_min: 0
sigma_max: 0

# Training
train_batch_size: 32
test_batch_size: 16
num_workers: 4
num_epochs: 100

ckp_interval: 1

# Optimizer
learning_rate: 1e-4
weight_decay: 0

# Losses 
loss:
  MSE: True
  L1: False

# Metrics
metrics:
  PSNR: True
  SSIM: True
  LPIPS: True
  NIQE: False

# Logging and visualisation
wandb_vis: True
verbose: True
plot_images: True
img_log_epochs: 5




